Car/urls.py
from django.urls import path
from .views import car_list, car_detail, car_add, car_edit, car_delete

app_name = 'Car'

urlpatterns = [
    path('list/', car_list, name='car_list'),
    path('<int:pk>/', car_detail, name='car_detail'),
    path('add/', car_add, name='car_add'),
    path('<int:pk>/edit/', car_edit, name='car_edit'),
    path('<int:pk>/delete/', car_delete, name='car_delete'),
]

CarMark/urls.py
from django.urls import path
from .views import carmark_list, carmark_detail, carmark_add, carmark_edit, carmark_delete

app_name = 'CarMark'

urlpatterns = [
    path('list_mark/', carmark_list, name='carmark_list'),
    path('<int:pk>/', carmark_detail, name='carmark_detail'),
    path('add/', carmark_add, name='carmark_add'),
    path('<int:pk>/edit/', carmark_edit, name='carmark_edit'),
    path('<int:pk>/delete/', carmark_delete, name='carmark_delete'),
]

CarModel/urls.py
from django.urls import path
from .views import carmodel_list, carmodel_detail, carmodel_add, carmodel_edit, carmodel_delete

app_name = 'CarModel'

urlpatterns = [
    path('list_model/', carmodel_list, name='carmodel_list'),
    path('<int:pk>/', carmodel_detail, name='carmodel_detail'),
    path('add/', carmodel_add, name='carmodel_add'),
    path('<int:pk>/edit/', carmodel_edit, name='carmodel_edit'),
    path('<int:pk>/delete/', carmodel_delete, name='carmodel_delete'),
]

carental/urls.py
from .views import accueil, car_list
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Car/', include('Car.urls')),
    path('CarModel/', include('CarModel.urls')),
    path('CarMark/', include('CarMark.urls')),
    path('', accueil, name='accueil'),
    path('accounts/login/', LoginView.as_view(), name='login'),  # Configuration de l'URL de connexion
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Car/models.py
from django.db import models
from CarMark.models import CarMark
from CarModel.models import CarModel
from django.contrib.humanize.templatetags.humanize import intcomma


# Create your models here.

class Car(models.Model):
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE)
    mark = models.ForeignKey(CarMark, on_delete=models.CASCADE)
    registration_number = models.CharField(max_length=20)
    year = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='cars/', blank=True, null=True)

    class Meta:
        verbose_name = "Voiture"
        verbose_name_plural = "Voitures"
        
    def __str__(self):
        return f"{self.mark} - {self.model}"
    
    def formatted_price(self):
        return intcomma(int(self.price))
    

CarMark/models.py
from django.db import models

# Create your models here.

class CarMark(models.Model):
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='logos/', blank=True, null=True)

    class Meta:
        verbose_name = "Marque"
        verbose_name_plural = "Marques"

    def __str__(self):
        return f"{self.name}"

CarModel/models.py
from django.db import models
from CarMark.models import CarMark
# Create your models here.

class CarModel(models.Model):
    name = models.CharField(max_length=100)
    year = models.PositiveIntegerField()
    mark = models.ForeignKey(CarMark, on_delete=models.CASCADE)
    
    
    class Meta:
        verbose_name = "Modèle"
        verbose_name_plural = "Modèles"

    def __str__(self):
        return f"{self.name}"

CarMark/forms.py
from django import forms
from .models import CarMark


class CarMarkForm(forms.ModelForm):
    class Meta:
        model = CarMark
        fields = '__all__'

CarMark/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import CarMark
from .forms import CarMarkForm
from django.contrib.auth.decorators import login_required


# Create your views here.

def carmark_list(request):
    carmarks = CarMark.objects.all() 
    return render(request, 'carmark/index.html', {'carmarks': carmarks}) # carmarks est le nom de la variable qui sera utilisée dans le template

def carmark_detail(request, pk):
    carmark = get_object_or_404(CarMark, pk=pk)
    return render(request, 'carmark/show.html', {'carmark': carmark})

def carmark_add(request):
    if request.method == 'POST': 
        form = CarMarkForm(request.POST, request.FILES) # request.FILES pour les fichiers
        if form.is_valid():
            form.save() # enregistre les données dans la base de données
            return redirect('CarMark:carmark_add') # carmark_list est le nom de la vue défini dans urls.py
    else:
        form = CarMarkForm() # crée un formulaire vide
    return render(request, 'carmark/create.html', {'form': form}) # form est le nom de la variable qui sera utilisée dans le template

@login_required
def carmark_edit(request, pk):
    carmark = get_object_or_404(CarMark, pk=pk) # pk est la clé primaire de l'objet à modifier
    if request.method == 'GET':
        form = CarMarkForm(request.POST, instance=carmark) # instance permet de pré-remplir le formulaire avec les données de l'objet à modifier
        if form.is_valid():
            form.save()
            return redirect('CarMark:carmark_list') # carmark_list est le nom de la vue défini dans urls.py
    else:
        form = CarMarkForm(instance=carmark) # crée un formulaire pré-rempli avec les données de l'objet à modifier
    return render(request, 'carmark/update.html', {'form': form}) 

@login_required
def carmark_delete(request, pk): 
    carmark = get_object_or_404(CarMark, pk=pk) 
    if request.method == 'GET':
        carmark.delete()
        return HttpResponseRedirect(reverse('CarMark:carmark_list'))  # Redirige vers la liste des voitures après la suppression
    return HttpResponse("Méthode non autorisée", status=405)

CarMark/templates/carmark/create.html
{% extends "structure.html" %}

{% block content %}
    <!-- Formulaire d'ajout de marque de voiture -->
    <h1>Ajouter une marque de voiture</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Ajouter">
    </form>
    <a href="{% url 'CarMark:carmark_list' %}">Retour</a>
{% endblock %}

CarMark/templates/carmark/index.html
{% extends "structure.html" %}

{% block content %}
    <!-- Contenu de la page d'accueil -->
    <h1 class="title">Liste des marques</h1>
    <a href="{% url 'CarMark:carmark_add' %}">Ajouter une marque</a>
    <ul class="car-list">
        {% for carmark in carmarks %}
            <li class="car-item">
                <a href="{% url 'CarMark:carmark_list' %}">
                </a>
                <a href="{% url 'CarMark:carmark_detail' carmark.id %}"> <img src="{{ carmark.logo.url }}" alt="" class="car-logo"></a>
                
            </li>
        {% endfor %}
    </ul>
{% endblock %}

CarMark/templates/carmark/show.html
{% extends "structure.html" %}

{% block content %}
    <!-- Détail de la marque de voiture -->
    <h1>{{ carmark.name }}</h1>
    <h4>Pays d'origine : {{ carmark.country }}</h4>
    <img src="{{ carmark.logo.url }}" alt="{{ carmark.name }}" class="car-logo">
    <a href="{% url 'CarMark:carmark_list' %}">Retour</a>
    <a href="{% url 'CarMark:carmark_edit' carmark.id %}">Modifier</a>
    <a href="{% url 'CarMark:carmark_delete' carmark.id %}">Supprimer</a>
    <h3>Les modèles de la marque</h3>
    <ul>
        {% for carmodel in carmark.carmodel_set.all %}
            <li><a href="{% url 'CarModel:carmodel_detail' carmodel.pk %}">{{ carmodel.name }}</a></li>
        {% endfor %}
    <h3>Les voitures de la marque</h3>
    <ul>
        {% for car in carmark.car_set.all %}
            <li><a href="{% url 'Car:car_detail' car.pk %}">{{ car.registration_number }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

CarMark/templates/carmark/update.html
{% extends "structure.html" %}
{% block content %}
<h1>Modifier la Voiture</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enregistrer</button>
</form>
<a href="{% url 'CarMark:carmark_list' %}">Retour</a>
{% endblock %}