Car/urls.py
from django.urls import path
from .views import car_list, car_detail, car_add, car_edit, car_delete

app_name = 'Car'

urlpatterns = [
    path('list/', car_list, name='car_list'),
    path('<int:pk>/', car_detail, name='car_detail'),
    path('add/', car_add, name='car_add'),
    path('<int:pk>/edit/', car_edit, name='car_edit'),
    path('<int:pk>/delete/', car_delete, name='car_delete'),
]

carental/urls.py
from .views import accueil, car_list
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Car/', include('Car.urls')),
    path('CarModel/', include('CarModel.urls')),
    path('CarMark/', include('CarMark.urls')),
    path('', accueil, name='accueil'),
    path('accounts/login/', LoginView.as_view(), name='login'),  # Configuration de l'URL de connexion
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Car/models.py
from django.db import models
from CarMark.models import CarMark
from CarModel.models import CarModel
from django.contrib.humanize.templatetags.humanize import intcomma


# Create your models here.

class Car(models.Model):
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE)
    mark = models.ForeignKey(CarMark, on_delete=models.CASCADE)
    registration_number = models.CharField(max_length=20)
    year = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='cars/', blank=True, null=True)

    class Meta:
        verbose_name = "Voiture"
        verbose_name_plural = "Voitures"
        
    def __str__(self):
        return f"{self.mark} - {self.model}"
    
    def formatted_price(self):
        return intcomma(int(self.price))
    

Car/forms.py
from django import forms
from .models import Car

class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = '__all__'

Car/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Car
from .forms import CarForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def car_list(request):
    cars = Car.objects.all()
    return render(request, 'car/index.html', {'cars': cars})

def car_detail(request, pk):
    car = get_object_or_404(Car, pk=pk)
    return render(request, 'car/show.html', {'car': car})


def car_add(request):
    if request.method == 'POST':
        form = CarForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Car:car_list'))  # Rediriger vers la liste des voitures après l'ajout réussi
    else:
        form = CarForm()
    return render(request, 'car/create.html', {'form': form})

@login_required
def car_edit(request, pk):
    car = get_object_or_404(Car, pk=pk)
    if request.method == 'POST':
        form = CarForm(request.POST, instance=car)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Car:car_list'))  # Redirige vers la liste des voitures après la modification
    else:
        form = CarForm(instance=car)
    return render(request, 'car/update.html', {'form': form})

@login_required
def car_delete(request, pk):
    car = get_object_or_404(Car, pk=pk)
    if request.method == 'GET':
        car.delete()
        return HttpResponseRedirect(reverse('Car:car_list'))  # Redirige vers la liste des voitures après la suppression
    return HttpResponse("Méthode non autorisée", status=405)  # 405 est le code d'erreur "Méthode non autorisée"

Car/templates/car/create.html
{% extends "structure.html" %}
{% block content %}
<div class="container">
    <h1>Ajouter une Voiture</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enregistrer</button>
    </form>
    <a href="{% url 'Car:car_list' %}">Retour</a>
</div>
{% endblock %}

Car/templates/car/index.html
{% extends "structure.html" %}
{% load static %}
{% block title %}Véhicules{% endblock %}
{% block content %}
    <div class="banner-images">
        <img src="{% static 'images/banner3.png' %}" alt="" class="banner-image">
    </div>
    <h1 class="title">Liste des véhicules</h1>
    <a href="{% url 'Car:car_add' %}" class="btn btn-primary">Ajouter un véhicule</a>
    {% for car in cars %}
    <div class="car">
       <img src="{{ car.image.url }}" alt="" class="car-image">
       <a href="{% url 'Car:car_detail' car.pk %}" class="btn btn-info">Voir plus</a>
        <div class="car-info">
            <h3>{{ car.mark }} {{ car.model }}</h3>
            <h4>Prix : {{ car.formatted_price }} FCFA/J</p>
        </div>
    </div>
{% endfor %}

{% endblock %}

Car/templates/car/show.html
{% extends "structure.html" %}
{% block content %}
<h1>Détails de la Voiture</h1>
<h4>Marque : {{ car.mark }}</h4>
<h4>Modèle : {{ car.model }}</h4>
<h4>Immatriculation : {{ car.registration_number }}</h4>
<h4>Année : {{ car.year }}</h4>
<h4>Prix : {{ car.formatted_price }} FCFA/J</h4>
<img src="{{ car.image.url }}" alt="{{ car.mark }} - {{ car.model }}">
<a href="{% url 'Car:car_edit' car.pk %}">Modifier</a>
<a href="{% url 'Car:car_delete' car.pk %}">Supprimer</a>
<a href="{% url 'Car:car_list' %}">Retour</a>
{% endblock %}

Car/templates/car/update.html
{% extends "structure.html" %}
{% block content %}
<h1>Modifier la Voiture</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enregistrer</button>
</form>
<a href="{% url 'Car:car_list' %}">Retour</a>
{% endblock %}