Car/urls.py
from django.urls import path
from .views import car_list, car_detail, car_add, car_edit, car_delete

app_name = 'Car'

urlpatterns = [
    path('list/', car_list, name='car_list'),
    path('<int:pk>/', car_detail, name='car_detail'),
    path('add/', car_add, name='car_add'),
    path('<int:pk>/edit/', car_edit, name='car_edit'),
    path('<int:pk>/delete/', car_delete, name='car_delete'),
]

CarModel/urls.py
from django.urls import path
from .views import carmodel_list, carmodel_detail, carmodel_add, carmodel_edit, carmodel_delete

app_name = 'CarModel'

urlpatterns = [
    path('list_model/', carmodel_list, name='carmodel_list'),
    path('<int:pk>/', carmodel_detail, name='carmodel_detail'),
    path('add/', carmodel_add, name='carmodel_add'),
    path('<int:pk>/edit/', carmodel_edit, name='carmodel_edit'),
    path('<int:pk>/delete/', carmodel_delete, name='carmodel_delete'),
]

carental/urls.py
from .views import accueil, car_list
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Car/', include('Car.urls')),
    path('CarModel/', include('CarModel.urls')),
    path('CarMark/', include('CarMark.urls')),
    path('', accueil, name='accueil'),
    path('accounts/login/', LoginView.as_view(), name='login'),  # Configuration de l'URL de connexion
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Car/models.py
from django.db import models
from CarMark.models import CarMark
from CarModel.models import CarModel
from django.contrib.humanize.templatetags.humanize import intcomma


# Create your models here.

class Car(models.Model):
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE)
    mark = models.ForeignKey(CarMark, on_delete=models.CASCADE)
    registration_number = models.CharField(max_length=20)
    year = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='cars/', blank=True, null=True)

    class Meta:
        verbose_name = "Voiture"
        verbose_name_plural = "Voitures"
        
    def __str__(self):
        return f"{self.mark} - {self.model}"
    
    def formatted_price(self):
        return intcomma(int(self.price))
    

CarModel/models.py
from django.db import models
from CarMark.models import CarMark
# Create your models here.

class CarModel(models.Model):
    name = models.CharField(max_length=100)
    year = models.PositiveIntegerField()
    mark = models.ForeignKey(CarMark, on_delete=models.CASCADE)
    
    
    class Meta:
        verbose_name = "Modèle"
        verbose_name_plural = "Modèles"

    def __str__(self):
        return f"{self.name}"

CarModel/forms.py
from django import forms
from .models import CarModel 
class CarModelForm(forms.ModelForm):
    class Meta:
        model = CarModel
        fields = '__all__'  

CarModel/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import CarModel
from .forms import CarModelForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def carmodel_list(request):
    carmodels = CarModel.objects.all()
    return render(request, 'carmodel/index.html', {'carmodels': carmodels})

def carmodel_detail(request, pk):
    carmodel = get_object_or_404(CarModel, pk=pk)
    return render(request, 'carmodel/show.html', {'carmodel': carmodel})

def carmodel_add(request):
    if request.method == 'POST':
        form = CarModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('CarModel:carmodel_add')
    else:
        form = CarModelForm()
    return render(request, 'carmodel/create.html', {'form': form})
@login_required
def carmodel_edit(request, pk):
    carmodel = get_object_or_404(CarModel, pk=pk)
    if request.method == 'POST':
        form = CarModelForm(request.POST, instance=carmodel)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('CarModel:carmodel_list'))
    else:
        form = CarModelForm(instance=carmodel)
    return render(request, 'carmodel/update.html', {'form': form})
@login_required
def carmodel_delete(request, pk):
    carmodel = get_object_or_404(CarModel, pk=pk)
    if request.method == 'GET':
        carmodel.delete()
        return HttpResponseRedirect(reverse('CarModel:carmodel_list'))
    return HttpResponse("Méthode non autorisée", status=405)

CarModel/templates/carmodel/create.html
{% extends "structure.html" %}

{% block content %}
    <!-- Contenu de la page d'accueil -->
    <h1>Ajouter un modèle de voiture</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Ajouter">
    </form>
    <a href="{% url 'CarModel:carmodel_list' %}">Retour</a>
{% endblock %}

CarModel/templates/carmodel/index.html
{% extends "structure.html" %}
{% load static %}
{% block title %}Les modèles{% endblock %}
{% block content %}
    <div class="banner-images">
        <img src="{% static 'images/banner1.png' %}" alt="" class="banner-image">
    </div>
    <h1 class="title">Liste des modèles de voiture</h1>
    <a href="{% url 'CarModel:carmodel_add' %}" class="btn btn-primary">Ajouter un modèle</a>
    <ul class="car-list">
        {% for carmodel in carmodels %}
            <li class="car-item">
                <a href="{% url 'CarModel:carmodel_detail' carmodel.pk %}">
                    <div class="car-name">{{ carmodel.name }}</div>
                </a>
                <img src="{{ carmodel.logo.url }}" alt="" class="car-logo">
            </li>
        {% endfor %}
    </ul>
{% endblock %}

CarModel/templates/carmodel/show.html
{% extends "structure.html" %}

{% block content %}
    <!-- Contenu de la page d'accueil -->
    <h1>Détail du modèle de voiture</h1>
    <h3>Nom du modèle : {{ carmodel.name }} </h3>
    <h3>Marque : {{ carmodel.mark }} </h3>
    <a href="{% url 'CarModel:carmodel_list' %}">Retour</a>
    <a href="{% url 'CarModel:carmodel_edit' carmodel.pk %}">Modifier</a>
    <a href="{% url 'CarModel:carmodel_delete' carmodel.pk %}">Supprimer</a>
    <h3>Voitures</h3>
    <ul>
        {% for car in carmodel.car_set.all %}
            <li>{{ car.registration_number }}</li>
        {% endfor %}
{% endblock %}

CarModel/templates/carmodel/update.html
{% extends "structure.html" %}

{% block content %}
    <!-- Contenu de la page d'accueil -->
    <h1>Modifier un modèle de voiture</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Modifier">
    </form>
{% endblock %}