Car/urls.py
from django.urls import path
from .views import car_list, car_detail, car_add, car_edit, car_delete

app_name = 'Car'

urlpatterns = [
    path('list/', car_list, name='car_list'),
    path('<int:pk>/', car_detail, name='car_detail'),
    path('add/', car_add, name='car_add'),
    path('<int:pk>/edit/', car_edit, name='car_edit'),
    path('<int:pk>/delete/', car_delete, name='car_delete'),
]

CarMark/urls.py
from django.urls import path
from .views import carmark_list, carmark_detail, carmark_add, carmark_edit, carmark_delete

app_name = 'CarMark'

urlpatterns = [
    path('list_mark/', carmark_list, name='carmark_list'),
    path('<int:pk>/', carmark_detail, name='carmark_detail'),
    path('add/', carmark_add, name='carmark_add'),
    path('<int:pk>/edit/', carmark_edit, name='carmark_edit'),
    path('<int:pk>/delete/', carmark_delete, name='carmark_delete'),
]

CarModel/urls.py
from django.urls import path
from .views import carmodel_list, carmodel_detail, carmodel_add, carmodel_edit, carmodel_delete

app_name = 'CarModel'

urlpatterns = [
    path('list_model/', carmodel_list, name='carmodel_list'),
    path('<int:pk>/', carmodel_detail, name='carmodel_detail'),
    path('add/', carmodel_add, name='carmodel_add'),
    path('<int:pk>/edit/', carmodel_edit, name='carmodel_edit'),
    path('<int:pk>/delete/', carmodel_delete, name='carmodel_delete'),
]

carental/urls.py
from .views import accueil, car_list
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Car/', include('Car.urls')),
    path('CarModel/', include('CarModel.urls')),
    path('CarMark/', include('CarMark.urls')),
    path('', accueil, name='accueil'),
    path('accounts/login/', LoginView.as_view(), name='login'),  # Configuration de l'URL de connexion
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home.html
{% extends "structure.html" %}
{% load static %}

{% block title %}Accueil{% endblock %}

{% block content %}
<div class="banner-images">
    <img class="banner-left" src="{% static 'images/banner-left.png' %}" alt="Logo du site">
    <h1 class="banner-center">Bienvenue sur CARENTAL</h1>
    <img class="banner-right" src="{% static 'images/banner-right.png' %}" alt="Logo du site">
</div>
<div class="container">
    <h2 class="title">Nos 05 véhicules les plus demandés</h2>
    <div class="car-grid">
        {% for Car in Cars|slice:":5" %}
            <div class="car">
                <img src="{{ Car.image.url }}" alt="{{ Car.mark }} {{ Car.model }}" class="car-image">
                <div class="car-info">
                    <h3>{{ Car.mark }} {{ Car.model }}</h3>
                    <h5>Prix : {{ Car.formatted_price }} FCFA/J</h5>
                </div>                
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/structure.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <!-- Ajout de Bootstrap pour les styles et les boutons -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="bg-primary py-2">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
                <a class="navbar-brand" href="{% url 'accueil' %}">
                    <img src="{% static 'images/mon_logo.JPG' %}" alt="Logo du site" class="logo">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accueil' %}">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'Car:car_list' %}">Voitures</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'CarMark:carmark_list' %}">Marques</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'CarModel:carmodel_list' %}">Modèles</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <div class="container">
        {% block content %}
        <!-- Le contenu spécifique à chaque page sera inclus ici -->
        {% endblock %}
    </div>

    <footer class="bg-primary text-light py-3">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; 2023 CARENTAL SARL. Tous droits réservés.</p>
                </div>
                <div class="col-md-6 text-right">
                    <a href="mailto:landrykoffi@cesag.edu.sn" class="text-light">carental@info.sn <i class="fa fa-envelope"></i></a>
                    <a href="https://m.facebook.com/" target="_blank" class="text-light"><i class="fab fa-facebook"></i></a>
                    <a href="https://www.linkedin.com/in/regis-koffi/" target="_blank" class="text-light"><i class="fab fa-linkedin"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <!-- Ajout de Bootstrap pour les scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>